### ISSUE TITLE
[FEA] dask-cudf should expose cudf functions that don't have dask equivalents

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cudf#133]
cudf has functions which don't have dask analogues.

For example:
```
import cudf, dask_cudf

df = cudf.DataFrame()
df['ones'] = [1, 1, 1]

ddf = dask_cudf.from_cudf(df, npartitions=1)
ddf['ones'].to_gpu_array()
```

Result:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-912c9fd2ec6f> in <module>
      8 ddf = dask_cudf.from_cudf(df, npartitions=1)
      9 
---> 10 ddf['ones'].to_gpu_array()

AttributeError: 'Series' object has no attribute 'to_gpu_array'
```

For a cudf user, this error is confusing. I went to look at cudf's API to see if cudf dropped this function before realizing it just doesn't exist in dask-cudf.

Other similar functions include `to_gpu_matrix`, `as_gpu_matrix`, `from_gpu_matrix`.

Instead of adding such methods to dask-cudf, would it make sense to catch this type of `Series` or `DataFrame` `has no attribute` error and attempt to have each partition call the given cudf function?

If so, it would help avoid the user pain of needing to fall back to `dask.delayed` workarounds.

**Comment by randerzander** [comment]
For posterity, here's the full workaround for using `to_device_array` with nvstrings, which was the original motivation for feature request:
```
import dask.delayed
import nvstrings

def do_cudf(df):
    df['ones_str'] = nvstrings.itos(df['ones'].astype('int32').to_gpu_array())
    return df
    
parts = [dask.delayed(do_cudf)(x) for x in ddf.to_delayed()]
ddf = dask_cudf.from_delayed(parts)
```

**Comment by mrocklin** [comment]
I think that we might try to solve this in the same way that Pandas did with extension namespaces.  cc @TomAugspurger

So dask-cudf would establish a namespace in dask.dataframe, like `.cudf`, and the dask-cudf project would populate that.

This would mean that you would do something like

```python
df.cuda.to_gpu_array()
```

You can also do things today like 

    ddf['ones'].values

or 

    ddf['ones'].map_partitions(my_cudf_to_gpu_array_function)

And those should work, though I acknowledge that at least the second probably won't be as nice.  The first seems like it should be doable though if `cudf.DataFrame.values` returns the kind of thing that you're looking for and if that thing looks enough like a numpy array to convince Dask Array to take over.

**Comment by mrocklin** [comment]
In general though I'm also fine with adding methods to dask-cudf.  I'd like to look at these on a case by case basis though, and see if there is some more general way to do things.

**Comment by galipremsagar** [comment]
I have a similar requirement. I'd like to use `insert` function exposed by nvstrings, which can be accessed by 
a `cudf` data frame but not a `dask-cudf` dataframe.

```python
import cudf
x = cudf.DataFrame({'a':["abcs","hfus"],'b':["abcs","hfus"],'c':["abcs","hfus"]})
print(x.a.str.insert(0, "rdg"))
0    rdgabcs
1    rdghfus
dtype: object
```

```python
import dask_cudf
y = dask_cudf.from_cudf(x,npartitions=1)
print(y.a.str.insert(0, "rdg"))
```

currently we get exception :
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-48e506ff92f4> in <module>
      1 import dask_cudf
      2 y = dask_cudf.from_cudf(x,npartitions=1)
----> 3 print(y.a.str.insert(0, "rdg"))

/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/accessor.py in __getattr__(self, key)
     86                 return partial(self._function_map, key)
     87         else:
---> 88             raise AttributeError(key)
     89 
     90 

AttributeError: insert
```


Current workaround is doing the same operation in a map_partitions call:
```python
def custom_insert(df, index, st):
    return df.a.str.insert(index, st)
sy = y.map_partitions(custom_insert, 0, "rdg", meta=('O'))
print(sy.compute())
0    rdgabcs
1    rdghfus
dtype: object
```

**Comment by mrocklin** [comment]
This should be relatively straightforward to resolve.  I think that the relevant code is here:

https://github.com/dask/dask/blob/ee1b6268f7165162eec998d909ee74e75922aa45/dask/dataframe/accessor.py#L103-L111

Instead of hard-coding Pandas there we should do something lilke 

```python
@property
def _accessor(self):
    return getattr(self._series._meta, self._accessor_name)
```

I'll add this to my todo list for the week, though as a warning it's relatively long at the moment.  If anyone else wants to pick this up that would be welcome.

**Comment by mrocklin** [comment]
See https://github.com/dask/dask/pull/4955

**Comment by mrocklin** [comment]
@galipremsagar your issue should be resolved if you try dask master

**Comment by galipremsagar** [comment]
I just verified this by building from master (my dask.__version is `1.2.2+87.g5406d77` ) and still face the same exception for the above sample.

cc: @mrocklin

**Comment by galipremsagar** [comment]
Looks like I'm now not able to perform few previous operations also which I was able to do previously..like: `.str.contains()`

**Comment by mrocklin** [comment]
https://github.com/rapidsai/dask-cudf/pull/289
