### ISSUE TITLE
[BUG] Drop fails

### ISSUE THREAD

**Issue by quasiben** [rapidsai/dask-cudf#158]
Drop is exposed in cudf but currently fails.  Below is a small example of the failure:

```python
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import cudf, dask_cudf

In [2]: cdf = cudf.DataFrame(dict(a=[1,2,3], b=[1,2,3]))

In [3]: ddf = dask_cudf.from_cudf(cdf, npartitions=1)

In [4]: ddf.head().to_pandas()
/home/nfs/bzaitlen/GitRepos/dask/dask/dataframe/core.py:4494: UserWarning: Insufficient elements for `head`. 5 elements requested, only 3 elements available. Try passing larger `npartitions` to `head`.
  warnings.warn(msg.format(n, len(r)))
Out[4]:
   a  b
0  1  1
1  2  2
2  3  3

In [5]: ddf.drop('a')
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-6-78e7014f52a4> in <module>
----> 1 ddf.drop('a')

~/GitRepos/dask/dask/dataframe/core.py in drop(self, labels, axis, errors)
   2860         if axis == 1:
   2861             return self.map_partitions(M.drop, labels, axis=axis, errors=errors)
-> 2862         raise NotImplementedError("Drop currently only works for axis=1")
   2863
   2864     def merge(self, right, how='inner', on=None, left_on=None, right_on=None,

NotImplementedError: Drop currently only works for axis=1

In [6]: ddf.drop('a', axis=1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/GitRepos/dask/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    159     try:
--> 160         yield
    161     except Exception as e:

~/GitRepos/dask/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3696     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3697         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3698

~/GitRepos/dask/dask/utils.py in __call__(self, obj, *args, **kwargs)
    715     def __call__(self, obj, *args, **kwargs):
--> 716         return getattr(obj, self.method)(*args, **kwargs)
    717

TypeError: drop() got an unexpected keyword argument 'axis'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-7-08db29a67847> in <module>
----> 1 ddf.drop('a', axis=1)

~/GitRepos/dask/dask/dataframe/core.py in drop(self, labels, axis, errors)
   2859         axis = self._validate_axis(axis)
   2860         if axis == 1:
-> 2861             return self.map_partitions(M.drop, labels, axis=axis, errors=errors)
   2862         raise NotImplementedError("Drop currently only works for axis=1")
   2863

~/GitRepos/dask/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    559         >>> ddf.map_partitions(func).clear_divisions()  # doctest: +SKIP
    560         """
--> 561         return map_partitions(func, self, *args, **kwargs)
    562
    563     @insert_meta_param_description(pad=12)

~/GitRepos/dask/dask/dataframe/core.py in map_partitions(func, *args, **kwargs)
   3733
   3734     if meta is no_default:
-> 3735         meta = _emulate(func, *args, udf=True, **kwargs2)
   3736     else:
   3737         meta = make_meta(meta, index=meta_index)

~/GitRepos/dask/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3695     """
   3696     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3697         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3698
   3699

~/miniconda3/envs/cudf-dev/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~/GitRepos/dask/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    175                 "{2}")
    176         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 177         raise ValueError(msg)
    178
    179

ValueError: Metadata inference failed in `drop`.

You have supplied a custom function and Dask is unable to
determine the type of output that that function returns.

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
TypeError("drop() got an unexpected keyword argument 'axis'")

Traceback:
---------
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/dataframe/utils.py", line 160, in raise_on_meta_error
    yield
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/dataframe/core.py", line 3697, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/utils.py", line 716, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
```

**Comment by quasiben** [comment]
I think this is an upstream issue with cudf not accepting an axis argument

**Comment by mrocklin** [comment]
https://github.com/rapidsai/cudf/issues/1074

**Comment by mrocklin** [comment]
;)

**Comment by mrocklin** [comment]
Was this fixed by https://github.com/rapidsai/cudf/pull/1396 ?

**Comment by randerzander** [comment]
> Was this fixed by [rapidsai/cudf#1396](https://github.com/rapidsai/cudf/pull/1396) ?

I don't believe so. In recent builds of cudf/dask-cudf I am still unable to drop columns:
```
import cudf, dask_cudf

df = cudf.DataFrame()
df['0'] = [0, 0, 0]
df['1'] = [1, 1, 1]

ddf = dask_cudf.from_cudf(df, npartitions=1)

ddf.drop('1', axis=1)
```

Trace:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    155     try:
--> 156         yield
    157     except Exception as e:

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3763     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3764         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3765 

/conda/envs/rapids/lib/python3.7/site-packages/dask/utils.py in __call__(self, obj, *args, **kwargs)
    756     def __call__(self, obj, *args, **kwargs):
--> 757         return getattr(obj, self.method)(*args, **kwargs)
    758 

TypeError: drop() got an unexpected keyword argument 'errors'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-2-a18580e57a0f> in <module>
      7 ddf = dask_cudf.from_cudf(df, npartitions=1)
      8 
----> 9 ddf.drop('1', axis=1)

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in drop(self, labels, axis, errors)
   2934         axis = self._validate_axis(axis)
   2935         if axis == 1:
-> 2936             return self.map_partitions(M.drop, labels, axis=axis, errors=errors)
   2937         raise NotImplementedError("Drop currently only works for axis=1")
   2938 

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    560         >>> ddf.map_partitions(func).clear_divisions()  # doctest: +SKIP
    561         """
--> 562         return map_partitions(func, self, *args, **kwargs)
    563 
    564     @insert_meta_param_description(pad=12)

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in map_partitions(func, *args, **kwargs)
   3800         # Use non-normalized kwargs here, as we want the real values (not
   3801         # delayed values)
-> 3802         meta = _emulate(func, *args, udf=True, **kwargs)
   3803     else:
   3804         meta = make_meta(meta, index=meta_index)

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3762     """
   3763     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3764         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3765 
   3766 

/conda/envs/rapids/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    171                 "{2}")
    172         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 173         raise ValueError(msg)
    174 
    175 

ValueError: Metadata inference failed in `drop`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
TypeError("drop() got an unexpected keyword argument 'errors'")

Traceback:
---------
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/utils.py", line 156, in raise_on_meta_error
    yield
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py", line 3764, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/utils.py", line 757, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
```

**Comment by mrocklin** [comment]
@rjzamora want to take a look at this as well?

**Comment by rjzamora** [comment]
@mrocklin - Sorry if this is not the right place for this, but could you explain a bit how `dask_cudf` and `dask` fit together?  

I can avoid this error by dropping the `errors` argument from the call to `map_partitions` [here](https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L2937).  However, I don't want to propose changes in `dask` if the real problem is in `dask_cudf`, but I'm just not understanding how everything fits together.

**Comment by mrocklin** [comment]
See https://blog.dask.org/2019/01/13/dask-cudf-first-steps

Dask dataframe was designed around Pandas.  We're now using that same code to also apply to cudf.  This requires cudf to look more like pandas than it currently does.  You're correct that we can't drop functionality from dask dataframe to support cudf (99% of Dask DataFrame use today is with with Pandas) so instead we add just enough functionality to cudf to make it close enough to pandas to fool the Dask Dataframe algorithms.  In this case, we need to add the `errors=` keyword to the cudf function, even if it doesn't do much.

**Comment by rjzamora** [comment]
Sounds good @mrocklin  - thanks!

**Comment by rjzamora** [comment]
@mrocklin @randerzander - I submitted a PR with a simple fix for this in `cudf` (https://github.com/rapidsai/cudf/pull/1680).  I'm new to the rapids workflow, so any advice/suggestions on getting my changes into `branch-0.8` are welcome :)

**Comment by randerzander** [comment]
Closing now that rapidsai/cudf#1680 merged

Thanks, @rjzamora!
